name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/hameconnes:latest

      - name: Generate .env file
        run: |
          echo "APP_NAME=Les Hameçonnés" > .env.production
          echo "APP_ENV=production" >> .env.production
          echo "APP_KEY=${{ secrets.APP_KEY || 'base64:VJ/YnYBfm7x/PX9vZTuR/mkyEsmgyAhvR/tGtTtYL34=' }}" >> .env.production
          echo "APP_DEBUG=false" >> .env.production
          echo "APP_URL=https://hameconnes.guillaume-rv.fr" >> .env.production

          echo "APP_LOCALE=fr" >> .env.production
          echo "APP_FALLBACK_LOCALE=en" >> .env.production
          echo "APP_FAKER_LOCALE=fr_FR" >> .env.production

          echo "LOG_CHANNEL=stack" >> .env.production
          echo "LOG_LEVEL=error" >> .env.production

          echo "DB_CONNECTION=mysql" >> .env.production
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.production
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.production
          echo "DB_DATABASE=${{ secrets.DB_NAME }}" >> .env.production
          echo "DB_USERNAME=${{ secrets.DB_USER }}" >> .env.production
          echo "DB_PASSWORD=\"${{ secrets.DB_PASS }}\"" >> .env.production
          echo "DB_CHARSET=${{ secrets.DB_CHARSET }}" >> .env.production

          echo "SESSION_DRIVER=database" >> .env.production
          echo "SESSION_LIFETIME=120" >> .env.production
          echo "SESSION_ENCRYPT=true" >> .env.production

          echo "BROADCAST_CONNECTION=log" >> .env.production
          echo "FILESYSTEM_DISK=local" >> .env.production
          echo "QUEUE_CONNECTION=database" >> .env.production

          echo "CACHE_STORE=database" >> .env.production

          echo "MAIL_MAILER=smtp" >> .env.production
          echo "MAIL_HOST=smtp.mailtrap.io" >> .env.production
          echo "MAIL_PORT=2525" >> .env.production
          echo "MAIL_USERNAME=null" >> .env.production
          echo "MAIL_PASSWORD=null" >> .env.production
          echo "MAIL_FROM_ADDRESS=noreply@hameconnes.guillaume-rv.fr" >> .env.production
          echo "MAIL_FROM_NAME=\"Les Hameçonnés\"" >> .env.production

          echo "VITE_APP_NAME=\"Les Hameçonnés\"" >> .env.production
          echo "VITE_MAPBOX_TOKEN=\"pk.eyJ1IjoiZ3VpbGxvciIsImEiOiJjazI0d25kZncyNnU5M2NtdmphaDR0bHcwIn0.XyxG_qYLs_RrQOwkFFomQg\"" >> .env.production

      - name: Deploy to O2switch via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/.env
            **/.env.*
            !**/.env.production

      - name: Rename .env.production to .env on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_IP }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd /home/hameconnes/www
            mv .env.production .env
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
